pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'us-east-2'
        BUCKET_NAME = 'cloud-final-joel'
        CLOUDFRONT_DIST_ID = 'E293OVOVYITHO5'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/Joey-The-Human/cloud-Computing-Final-Project.git'
            }
        }

        stage('Deploy HTML/CSS/JS to S3') {
            steps {
                bat """
                aws s3 cp "Cloud Computing Final Project/index.html" s3://%BUCKET_NAME%/index.html
                aws s3 cp "Cloud Computing Final Project/indexStyle.css" s3://%BUCKET_NAME%/indexStyle.css
                aws s3 cp "Cloud Computing Final Project/script.js" s3://%BUCKET_NAME%/script.js
                """
            }
        }


        stage('Sync Resources Folder') {
            steps {
                bat """
                aws s3 sync "Cloud Computing Final Project/Resources" s3://%BUCKET_NAME%/Resources
                """
            }
        }

        stage('Invalidate CloudFront Cache') {
            steps {
                bat """
                aws cloudfront create-invalidation --distribution-id %CLOUDFRONT_DIST_ID% --paths "/*"
                """
            }
        }
    }

    post {
        success {
            echo 'Deployment complete. Site is live at https://joelbowman.org'
        }
        failure {
            echo 'Deployment failed. Check logs for errors.'
        }
    }
}
